[rule.pandoc]
input = "{stem}.md"
outputs = ["${stem}.pdf"]
cmd = """
pandoc --standalone --citeproc --to=pdf --pdf-engine=lualatex --output=${stem}.pdf ${stem}.md
"""

[task.all]
inputs = ["manual.pdf", "termal-export-manual.pdf"]
