#!/usr/bin/env bash

# vim:ft=bash

set -u

# Takes an Expect script as generated by autoexpect, and modifies it so as to
# make it more useable by ./run-tests.sh.

# I delete lines 3-42 not because I don't like them, but because I don't need
# them in _all_ the test scripts.

# Then I add a `default` clause to all `expect` commands, so that the test
# _fails_ (instead of blithely proceeding) if an expect is not met.

sed '{
	3,42d;
	s/timeout -1/timeout 1/;
	s/^expect -exact \(.*\)$/expect {\n\texpect -exact \1 {} \n\tdefault { exit 1 }\n}/
	$a\
	\
# Gets the exit code of the spawned process, so that this script fails IFF it \
# did. \
catch wait result \
set prog_exit_code [lindex $result 3] \
exit $prog_exit_code
}' 
