#!/usr/bin/env bash

# vim:ft=bash

# Takes an Expect script as generated by autoexpect, and modifies it so as to
# make it more useable by ./run-tests.sh.

# I delete lines 3-42 now because I don't like them, but because I don't need
# them in _all_ the test scripts.

sed '{
	3,42d;
	s/timeout -1/timeout 1/;
	$a\
	\
# Gets the exit code of the spawned process, so that this script fails IFF it \
# did. \
catch wait result \
set prog_exit_code [lindex $result 3] \
exit $prog_exit_code
}'
