#!/usr/bin/expect -f

# This test checks that panics are caught.
#
package require cmdline

set options {
        {t.arg 1 "Expect timeout [s]"}
        {w.arg 500 "Crossterm poll wait time [ms]"}
}
set usage ": prog [options]"
array set params [::cmdline::getoptions argv $options $usage]

set pwt $params(w)
set timeout $params(t)


spawn ../target/debug/termal --poll-wait-time $pwt -w 15 -t 9 --panic data/test-aln-02.fas
send "q\r"
expect eof

# Gets the exit code of the spawned process, so that this script fails IFF it 
# did. 
catch wait result 
puts "termal exit code: $result"
set prog_exit_code [lindex $result 3] 
if { $prog_exit_code > 0 } {
	# We're expecting a failure
	exit 0
} else {
	puts "Expecting panic"
	exit 127
}
