#!/usr/bin/expect -f

# This test checks that panics are caught.
#
set timeout 1
spawn ../target/debug/termal -w 15 -t 9 data/test-aln-02.fas
send "q\r"
expect eof

# Gets the exit code of the spawned process, so that this script fails IFF it 
# did. 
catch wait result 
puts "termal exit code: $result"
set prog_exit_code [lindex $result 3] 
if { $prog_exit_code > 0 } {
	# We're expecting a failure
	exit 0
} else {
	puts "Expecting panic"
	exit 127
}
