#!/usr/bin/expect -f
#


package require cmdline

set options {
        {t.arg 1 "Expect timeout [s]"}
        {w.arg 500 "Crossterm poll wait time [ms]"}
}
set usage ": prog \[options]"
array set params [::cmdline::getoptions argv $options $usage]

set pwt $params(w)
set timeout $params(t)


spawn ../target/debug/termal --poll-wait-time $pwt -LB -w 12 -t 8 data/test-aln-02.fas
match_max 100000
expect {
	expect -exact "\[?1049h\[1;1H\[J\[2;1H\[J\[3;1H\[J\[4;1H\[J\[5;1H\[J\[6;1H\[J\[7;1H\[J\[8;1H\[J\[1;1H\[38;5;15m┌ data/test┐\[2;1H│\[38;2;255;165;0mAAAAAAAAAA\[38;5;15m│\[3;1H│\[38;2;255;165;0mAAAAAAAAAA\[38;5;15m│\[4;1H│\[38;2;255;165;0mAAAAAAAAAA\[38;5;15m│\[5;1H│\[38;5;1mDDDDDDDDDD\[38;5;15m│\[6;1H│\[38;5;1mDDDDDDDDDD\[38;5;15m│\[7;1H│\[38;5;1mDDDDDDDDDD\[38;5;15m│\[8;1H└──────────┘\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l" {} 
	default { exit 1 }
}
send -- "l"
expect {
	expect -exact "\[2;11H\[38;5;5mQ\[3;11HQ\[4;11HQ\[5;11HN\[6;11HN\[7;11HN\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l" {} 
	default { exit 1 }
}
send -- "j"
expect {
	expect -exact "\[4;2H\[38;5;1mDDDDDDDDD\[38;5;5mN\[7;2H\[38;5;2mWWWWWWWWW\[38;2;255;165;0mS\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l" {} 
	default { exit 1 }
}
send -- "k"
expect {
	expect -exact "\[4;2H\[38;2;255;165;0mAAAAAAAAA\[38;5;5mQ\[7;2H\[38;5;1mDDDDDDDDD\[38;5;5mN\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l" {} 
	default { exit 1 }
}
send -- "h"
expect {
	expect -exact "\[2;11H\[38;2;255;165;0mA\[3;11HA\[4;11HA\[5;11H\[38;5;1mD\[6;11HD\[7;11HD\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l\[39m\[49m\[59m\[0m\[?25l" {} 
	default { exit 1 }
}
send -- "q"
expect eof
	
# Gets the exit code of the spawned process, so that this script fails IFF it 
# did. 
catch wait result 
set prog_exit_code [lindex $result 3] 
exit $prog_exit_code
