#!/usr/bin/expect -f

package require cmdline

set options {
        {t.arg 1 "Expect timeout [s]"}
        {w.arg 500 "Crossterm poll wait time [ms]"}
}
set usage ": prog [options]"
array set params [::cmdline::getoptions argv $options $usage]

set pwt $params(w)
set timeout $params(t)


spawn ../target/debug/termal --poll-wait-time $pwt -w 20 -t 10 ../data/test1.fas
send "q"
expect {
    eof { }
    default { exit 1 }
}
spawn ../target/debug/termal --poll-wait-time $pwt -w 20 -t 10 ../data/test1.fas
send "Q"
expect {
    eof { }
    default { exit 1 }
}
