#!/usr/bin/expect -f

package require cmdline

set options {
        {t.arg 100 "Expect timeout [ms]"}
        {w.arg 500 "Crossterm poll wait time [ms]"}
}
set usage ": prog \[options]"
array set params [::cmdline::getoptions argv $options $usage]

set pwt $params(w)
set timeout $params(t)


spawn ../target/debug/termal --poll-wait-time $pwt -LBC -w 11 -t 3 --no-zoom-box data/test-aln-01.fas
expect "AAAAAAAAA"
send "z"
expect {
	"mGGGCCC" { exit }
	default { exit 1 }
}

# Gets the exit code of the spawned process, so that this script fails IFF it 
# did. 
catch wait result 
set prog_exit_code [lindex $result 3] 
exit $prog_exit_code

