[package]
name = "termal-export"
version = "0.2.0"
edition = "2021"
publish = true

[dependencies]
termal-alignment = { path = "../termal-alignment" }
# if export_svg is implemented in this crate's lib, no extra deps here
clap = { version = "4", features = ["derive"] }
anyhow = "1"
itertools = "0.14.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
